FROM node:25-alpine3.22

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN rm -f /usr/local/bin/yarn /usr/local/bin/yarnpkg \
    && npm install -g corepack --no-update-notifier --no-fund \
    && corepack enable \
    && corepack prepare pnpm@latest --activate \
    && pnpm install --frozen-lockfile

COPY package.json ./
RUN pnpm install

COPY server/ .

EXPOSE 3001

CMD ["node", "main.js"]
