FROM node:25-alpine3.22 AS build

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN rm -f /usr/local/bin/yarn /usr/local/bin/yarnpkg \
 && npm install -g corepack --no-update-notifier --no-fund \
 && corepack enable \
 && corepack prepare pnpm@latest --activate \
 && pnpm install --frozen-lockfile

COPY . .

RUN pnpm build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
